### ISSUE TITLE
CRAN release planned?

### ISSUE THREAD

**Issue by JosiahParry** [crazycapivara/h3-r#36]
Hi there! 

I'm currently working on a package that utilizes functionality from Uber's h3. I have modified a fork for my own use (https://github.com/josiahparry/h3r). However, the package I have forked is not as mature as your own. 

Do you plan on releasing {h3} to CRAN? This will help me decide how I want to address the h3 dependency.

**Comment by crazycapivara** [comment]
@JosiahParry Yes, a CRAN release is planned but it must meet the [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html). Usually packages should run on all 3 major platforms, but h3 will not run under windows.
But I think this will be fine due to the remark "Packages will not normally be accepted that do not run on at least _two_ of the major R platforms." Furthermore, I have to deal with the H3 C-Lib dependency. I think the automated check after submission will fail, because of the missing dependency. Maybe it is enough to provide a `SystemsRequirements` field in the DESCRIPTION.
So, maybe I just submit it and see what I need to do that it gets accepted.

**Comment by dfellis** [comment]
Just wanted to note that h3 does work on Windows: https://github.com/uber/h3/blob/master/dev-docs/build_windows.md

**Comment by JosiahParry** [comment]
Thanks for the update. That’s great news. My C knowledge is super limited.
But I think the approach that h3-py takes might be a good one. They keep a
linked sub directory of the h3 source code based on a given commit for a
version. Then using cython build the package from source (or that’s what I
think is happening). There are makefiles for all major OS in there. I
suspect this same thing can be done for h3-r.

**Comment by crazycapivara** [comment]
@dfellis Yes, you are right. I just had no chance to try this and I'm not sure how easy it will be to bundle it for a CRAN release.

**Comment by JosiahParry** [comment]
@crazycapivara, I believe using the `SystemRequirements` field would suffice! :)

**Comment by dcooley** [comment]
For what it's worth I am also interested in getting ithis CRAN-ready too, so I made a version with the C library bundled in - https://github.com/dcooley/h3r, with only [one function](https://github.com/dcooley/h3r/blob/master/src/test.cpp) as a proof-of-concept. 

I forked your `h3-r` repo and tried to replicate this structure but I couldn't make it work.

**Comment by paleolimbot** [comment]
Thanks @dcooley for looping me in!

I was fooling around with this a few weeks ago...my thought was to bundle the C library (which works on Win). I'm using wk to avoid an sf (hence system GDAL) dependency and I'd like to align it with the [s2::s2_cell()](https://r-spatial.github.io/s2/reference/s2_cell.html) implementation, which does more or less the same thing but using the S2 index system. You all are welcome to use any of the code I've written so far ( https://github.com/paleolimbot/h3r ). There are other things that are priorities for me right now and I doubt I'll get what I wrote done fast enough for your collective use cases.

Probably the biggest difference is that I'm storing H3 indexes in `double()` vectors with a custom print method (like bit64 does)...this makes the implementation about twice as fast!

It's also worth noting that the H3 C library is so small and portable that you can include it in any package (I have it automated to ~60 lines of code here: https://github.com/paleolimbot/h3r/blob/master/data-raw/update-h3.R ).

**Comment by crazycapivara** [comment]
@dcooley Great. Looks promising. Just tested your proof of concept `h3r` and it works fine for me. Sometime ago a also tried to bundle it but I think I was missing something in `Makevars`.

Maybe in your fork of my `h3-r` you could not make it work by replicating your structure because you linked to a wrong `H3` Version? The bindings were written for Version 3.3.0 of `H3`. I just had a quick look and recognized, that there were some "breaking" changes like renaming structure `GeoPoint` => `LatLng` and all `lon` attributes to `lng`. See also [CHANGELOG](https://github.com/uber/h3/blob/master/CHANGELOG.md). Maybe we could first make it work bundled for Version 3.3.0 and in a next step switch to latest version. What do you think about it? I created an issue for the bundling #37. Would be great if we can manage it.

**Comment by crazycapivara** [comment]
Just created a new branch [feature/bundle-h3-c-lib](https://github.com/crazycapivara/h3-r/tree/feature/bundle-h3-c-lib) and added a script inspired by @paleolimbot to bundle to h3c lib but I get an error when compiling:

```
In file included from algos.c:33:0:
stackAlloc.h:59:2: error: #error "This platform does not support stack array allocation, please submit an issue on https://github.com/uber/h3 to report this error"
 #error \
  ^~~~~
```

**Comment by paleolimbot** [comment]
It looks like you're trying to bundle an old version (3.3)...I didn't get this error with v3.7.1!

**Comment by crazycapivara** [comment]
Hi @paleolimbot,
yes you are right, I wanted to test it with 3.3 because of the breaking changed in some naming. So that I wanted to switch to 3.7 in a next step but then maybe I have to do both steps at the same time :-)

**Comment by paleolimbot** [comment]
Also a quick note that your update script won't clean the previous version of H3 that you copied. Not a problem if you remember to do this manually every time, but I've been burned by this with s2, PROJ, and GEOS since I do the update a few times a year for those.

**Comment by dfellis** [comment]
> Hi @paleolimbot,
> yes you are right, I wanted to test it with 3.3 because of the breaking changed in some naming. So that I wanted to switch to 3.7 in a next step but then maybe I have to do both steps at the same time :-)

HI @crazycapivara, 3.7.1 should not have any breaking name changes? If you check out the `v3.7.1` tag, not the `master` branch, which we are working on breaking changes for 4.0.

Let me know if there really is a breaking change, though, as that was not supposed to happen.

**Comment by crazycapivara** [comment]
Thanks @dfellis for the information. So I will first try to switch to 3.7.1.

**Comment by crazycapivara** [comment]
Finally it works with v3.7.1 and removing brackets around `<faceijk.h>` in `h3Index.c`. Thanx to @paleolimbot for the update script with this remark in the end.

See #38
